spring:
  application:
    name: accounts-demo
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    show-sql: true
    properties:
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/accounts
    #for local tests:
    #url: jdbc:postgresql://localhost:5432/accounts
    username: myuser
    password: secret
